name: Periodic Health Check

on:
  schedule:
    - cron: '30 5 * * 1,3'
    # - cron: '30 5 * * 2,4'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        if: github.event.schedule != '10 8 * * 1,3'
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://pokedex-78yv.onrender.com/health
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false